server:
  port: ${SPRING_SERVER_PORT:8081}

spring:
  application:
    name: TodoApp-Dev
  datasource:
    url: jdbc:mysql://localhost:3306/employees
    username: root
    password: sra1kumar
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}